// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/location/location.proto

package locationpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Location struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Latitude      float64                `protobuf:"fixed64,2,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,3,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Timestamp     string                 `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Location) Reset() {
	*x = Location{}
	mi := &file_proto_location_location_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Location) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Location) ProtoMessage() {}

func (x *Location) ProtoReflect() protoreflect.Message {
	mi := &file_proto_location_location_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Location.ProtoReflect.Descriptor instead.
func (*Location) Descriptor() ([]byte, []int) {
	return file_proto_location_location_proto_rawDescGZIP(), []int{0}
}

func (x *Location) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Location) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *Location) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *Location) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

type Result struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Result) Reset() {
	*x = Result{}
	mi := &file_proto_location_location_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Result) ProtoMessage() {}

func (x *Result) ProtoReflect() protoreflect.Message {
	mi := &file_proto_location_location_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Result.ProtoReflect.Descriptor instead.
func (*Result) Descriptor() ([]byte, []int) {
	return file_proto_location_location_proto_rawDescGZIP(), []int{1}
}

func (x *Result) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_proto_location_location_proto protoreflect.FileDescriptor

const file_proto_location_location_proto_rawDesc = "" +
	"\n" +
	"\x1dproto/location/location.proto\x12\blocation\"~\n" +
	"\bLocation\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\blatitude\x18\x02 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x03 \x01(\x01R\tlongitude\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\tR\ttimestamp\" \n" +
	"\x06Result\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status2H\n" +
	"\x0fLocationTracker\x125\n" +
	"\rStoreLocation\x12\x12.location.Location\x1a\x10.location.ResultBDZBgithub.com/KirillKotovsky/location_proto/proto/location;locationpbb\x06proto3"

var (
	file_proto_location_location_proto_rawDescOnce sync.Once
	file_proto_location_location_proto_rawDescData []byte
)

func file_proto_location_location_proto_rawDescGZIP() []byte {
	file_proto_location_location_proto_rawDescOnce.Do(func() {
		file_proto_location_location_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_location_location_proto_rawDesc), len(file_proto_location_location_proto_rawDesc)))
	})
	return file_proto_location_location_proto_rawDescData
}

var file_proto_location_location_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_location_location_proto_goTypes = []any{
	(*Location)(nil), // 0: location.Location
	(*Result)(nil),   // 1: location.Result
}
var file_proto_location_location_proto_depIdxs = []int32{
	0, // 0: location.LocationTracker.StoreLocation:input_type -> location.Location
	1, // 1: location.LocationTracker.StoreLocation:output_type -> location.Result
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_location_location_proto_init() }
func file_proto_location_location_proto_init() {
	if File_proto_location_location_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_location_location_proto_rawDesc), len(file_proto_location_location_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_location_location_proto_goTypes,
		DependencyIndexes: file_proto_location_location_proto_depIdxs,
		MessageInfos:      file_proto_location_location_proto_msgTypes,
	}.Build()
	File_proto_location_location_proto = out.File
	file_proto_location_location_proto_goTypes = nil
	file_proto_location_location_proto_depIdxs = nil
}
